### ISSUE TITLE
Annual Report filing successful for a company in the "historical status due to amalgamation".

### ISSUE THREAD

**Issue by nsmenon8890** [bcgov/business-ar#150] opened 2024-05-29 18:08 UTC
After attempting to complete the annual report filing for a company that was historically inactive due to amalgamation, the filing was successfully processed. The status of the company changed from historical to active.

Test data used: BC0826103

Attaching the screen shot from event_table which shows the change from Historical(HAM) to Active (ACT)

Please provide more test data for tetsing where the company is historical due to other reasons.**

<img width="718" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL29lQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe8217d5f7754bbc4e3aea5820c3d4660d80fe1b/image.png" alt="image.png" />

<img width="1745" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzRlQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e9a4bd91804272b626b13a5ff6a07c19765bfbdb/image.png" alt="image.png" />

**Comment by MKagis** [comment] 2024-05-29 18:17
<img width="858" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3NmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cb4f791d2fa86d95d193f2a0744123f249876f7f/Amalgamation%20Application_BC1054220.PNG" alt="Amalgamation Application_BC1054220.PNG" />

**Comment by nsmenon8890** [comment] 2024-05-29 21:46
We also attempted voluntary dissolution filing, resulting in the company being voluntarily dissolved, and its status changing to Historical. Additionally, I successfully completed the AR filing in BCROS and the company was back to ACTIVE.

Test data used: BC0682196

<img width="923" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME1nQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--92f26016b3913ff78bdc15e8132c587069a5d4bc/image.png" alt="image.png" />

**Comment by nsmenon8890** [comment] 2024-05-29 21:47
<img width="1475" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFlnQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3b24854467ab1cbbc05a07642dd299ef582f76e8/image.png" alt="image.png" />
<img width="1499" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGdnQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5785f14fae490f6fd960e06484807261a59b3c40/image.png" alt="image.png" />


<img width="1504" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGtnQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d1f0be47c20330e12d91d34f83f8bd6fd5a49a2d/image.png" alt="image.png" />

<img width="1455" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHNnQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6bdf859e9ba669c7d6d4e2645eea5e2096c9b717/image.png" alt="image.png" />

**Comment by trishreimer** [comment] 2024-05-30 23:34
For this AR Campaign, we are selecting only active companies. This issue is important but not required for this initial release because of the data set that is being used to select the eligible corporations.
Moving to icebox for now.

**Comment by nsmenon8890** [comment] 2024-05-31 17:27
Hi team, 

We have different status codes " state_type_cd "for various filings, all of which have the operation code "op_state_type_cd". When all the ops_status is "ACT", the system allows filing of the AR. The exception applies to statuses state_type_cd =  "LRL" and "LIQ". I have attached a screenshot displaying the different status codes.

<img width="910" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMklxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--604863c5dc3c722871c223d2d6f2b89763ccbe03/image.png" alt="image.png" />

**Comment by dvdenis** [comment] 2024-05-31 17:34
The key difference is that all of the state_typ_cd codes above have the op_state_typ_cd of ACT, but when when the state_typ_cd is LIQ (in liquidation), or LRL (in limited restore liquidation), in COLIN they are not allowed to file annual reports, so those 2 sub-states should be blocked from being allowed to file ARs in BCROS.  All of the other ACT sub states can continue to file ARs in both applications.

**Comment by thorwolpert** [comment] 2024-06-01 21:19
On our resources.md we have this requirements link
https://docs.google.com/spreadsheets/d/1pwtBc0VHKsJPE72uzZxsePRbXs41CchV/edit#gid=2113868176

**Comment by deetz99** [comment] 2024-06-24 20:59
#231 
Shows the same alert for any business where the corpState does not equal 'ACT'

More work will be needed on the api to add specific error messages inline with the [requirements matrix](https://docs.google.com/spreadsheets/d/1pwtBc0VHKsJPE72uzZxsePRbXs41CchV/edit#gid=2113868176)

<img width="673" alt="Screenshot 2024-06-24 at 1 48 15 PM" src="https://github.com/bcgov/business-ar/assets/73151365/a0b0030a-71b1-4c69-87c6-feffdbff6931">

**Comment by nsmenon8890** [comment] 2024-07-08 19:26
Testing completed and working as expected.

<img width="1505" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3kvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--716403fc4f29c8237a2bcb992d6e1884d24478c5/image.png" alt="image.png" />

**Comment by nsmenon8890** [comment] 2024-07-08 20:25
Tried to file AR for a company which was historical due to amalgamation. The system prevented the entity from filing the Annual Report, indicating that it is an inactive business.

test data used BC0879913

<img width="1564" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBem5BQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--410fcb4b95fbd2896f11eb14fed31f3acfe847ab/image.png" alt="image.png" />

**Comment by thorwolpert** [comment] 2024-07-08 21:16
confirmed

**Closed by thorwolpert** 2024-07-08 21:16 UTC
Labels: Testing
