### ISSUE TITLE
BAR Payment - issue where the payment status code in the BAR database remained at "CREATED," preventing filings from syncing back to COLIN. 

### ISSUE THREAD

**Issue by nsmenon8890** [bcgov/business-ar#451] opened 2024-11-01 18:35 UTC
Starting Monday, October 28th, we encountered an issue where the payment status code in the BAR database remained at "CREATED," preventing filings from syncing back to COLIN. This issue has impacted approximately 60 companies, as they are unable to see confirmation that their payment has processed once they return to COLIN.

1) Problem is related to the queue service expired. Q service was not implemented in PROD.

This issue is related to a missing payment component in the BAR production environment. The application was expected to redirect users to a confirmation page after completing payment. However, from October 28-30, an issue with the payment process occurred: users paid through SBC Pay, their credit card transactions were successful, but the SBC pay page displayed a "failed" status. Consequently, users were not redirected to the confirmation page, leaving the payment status stuck at "PENDING."

The application is designed to handle such cases with a queue_service to manage unexpected errors from the payment side. However, this queue_service had not been deployed in production. After discussing the issue with Thor, he mentioned that there hadn’t been an opportunity to deploy it. I collaborated with Travis and Andriy to deploy the queue_service, ensuring BAR can handle unforeseen payment errors going forward.
 
In simpler terms, the redirection to the confirmation page after payment is like the "happy path" — it's what we expect to happen when everything works smoothly. The queue_service, on the other hand, acts as a backup plan in case that redirection doesn’t work. In BAR, this backup wasn’t deployed initially, which is why some payments got stuck in a "PENDING" status when users weren’t redirected correctly. Yesterday, we deployed the queue_service to production, so now BAR is equipped to handle these situations even if the redirection fails. But it is still worth investigation that why those payments went through but PAY displayed as failed for those three days.

**Comment by hanlunBCRegistries** [comment] 2024-11-04 21:34
Currently the issue is resolved, we can have a chat with PAY team to find out the root cause of the issue and make sure we are 100% confident

**Comment by seeker25** [comment] 2024-11-05 16:36
Root cause of the issue is already discussed above

**Comment by PCC199** [comment] 2024-11-13 23:02
@hanlunBCRegistries Can this issue be closed?

**Comment by nsmenon8890** [comment] 2024-11-13 23:04
@PCC199 Yes please

**Comment by hanlunBCRegistries** [comment] 2024-11-13 23:04
@PCC199 This issue has been resolved. @Maribeth-Wilson @ozamani9gh Do you think this ticket can be closed since the payment issue is resolved?

**Comment by PCC199** [comment] 2024-11-13 23:08
Closed as resolved

**Closed by PCC199** 2024-11-13 23:08 UTC
